apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling
spec:
  replicas: 4
  selector:
    matchLabels:
      app: rolling
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: rolling
        track: stable
    spec:
      containers:
        - name: rollingv1cd 
          image: linuxacademycontent/content-gcp-labs:rolling-v1
          ports:
            - name: http
              containerPort: 80
