CREATE TABLE IF NOT EXISTS MetObjects (
    `Object_Number` VARCHAR(50) CHARACTER SET utf8,
    `Is_Highlight` VARCHAR(5) CHARACTER SET utf8,
    `Is_Public_Domain` VARCHAR(5) CHARACTER SET utf8,
    `Object_ID` INT,
    `Department` VARCHAR(41) CHARACTER SET utf8,
    `Object_Name` VARCHAR(80) CHARACTER SET utf8,
    `Title` VARCHAR(837) CHARACTER SET utf8,
    `Culture` VARCHAR(98) CHARACTER SET utf8,
    `Period` VARCHAR(70) CHARACTER SET utf8,
    `Dynasty` VARCHAR(45) CHARACTER SET utf8,
    `Reign` VARCHAR(55) CHARACTER SET utf8,
    `Portfolio` VARCHAR(835) CHARACTER SET utf8,
    `Artist_Role` VARCHAR(1249) CHARACTER SET utf8,
    `Artist_Prefix` VARCHAR(1239) CHARACTER SET utf8,
    `Artist_Display_Name` VARCHAR(3574) CHARACTER SET utf8,
    `Artist_Display_Bio` TEXT CHARACTER SET utf8,
    `Artist_Suffix` VARCHAR(1281) CHARACTER SET utf8,
    `Artist_Alpha_Sort` TEXT CHARACTER SET utf8,
    `Artist_Nationality` VARCHAR(1445) CHARACTER SET utf8,
    `Artist_Begin_Date` VARCHAR(1935) CHARACTER SET utf8,
    `Artist_End_Date` VARCHAR(1935) CHARACTER SET utf8,
    `Object_Date` VARCHAR(239) CHARACTER SET utf8,
    `Object_Begin_Date` INT,
    `Object_End_Date` INT,
    `Medium` TEXT CHARACTER SET utf8,
    `Dimensions` VARCHAR(2172) CHARACTER SET utf8,
    `Credit_Line` VARCHAR(1142) CHARACTER SET utf8,
    `Geography_Type` VARCHAR(72) CHARACTER SET utf8,
    `City` VARCHAR(62) CHARACTER SET utf8,
    `State` VARCHAR(33) CHARACTER SET utf8,
    `County` VARCHAR(49) CHARACTER SET utf8,
    `Country` VARCHAR(75) CHARACTER SET utf8,
    `Region` VARCHAR(64) CHARACTER SET utf8,
    `Subregion` VARCHAR(50) CHARACTER SET utf8,
    `Locale` VARCHAR(83) CHARACTER SET utf8,
    `Locus` VARCHAR(81) CHARACTER SET utf8,
    `Excavation` VARCHAR(100) CHARACTER SET utf8,
    `River` VARCHAR(42) CHARACTER SET utf8,
    `Classification` VARCHAR(74) CHARACTER SET utf8,
    `Rights_and_Reproduction` VARCHAR(223) CHARACTER SET utf8,
    `Link_Resource` VARCHAR(53) CHARACTER SET utf8,
    `Metadata_Date` DATETIME,
    `Repository` VARCHAR(40) CHARACTER SET utf8
);
